updating readme.md
PoucaAgua/irrigation-design-system-backend pull request #44
Opened 2023-08-04 23:45 UTC by evandrosystems

2023-08-05 01:22 UTC, ravellys requested changes
remove the path .idea from the commit

2023-08-05 01:22 UTC, ravellys commented on .idea/.gitignore
please. remove this file from the commit

2023-08-05 01:22 UTC, ravellys commented on Readme.md
> +5. Environment variables
💯

2023-08-05 01:37 UTC, evandrosystems commented on .idea/.gitignore
Ok!

2023-08-05 02:21 UTC, evandrosystems commented on .idea/.gitignore
Done!

2023-08-07 21:13 UTC, ravellys commented on .idea/.gitignore
awesome

2023-08-07 21:14 UTC, ravellys approved these changes
LGTM

2023-08-10 01:25 UTC, merged