Percent wetted and percent shaded
PoucaAgua/irrigation-design-system-backend pull request #45
Opened 2023-08-07 21:29 UTC by geanderson-062

2023-08-07 22:25 UTC, ravellys requested changes
Create a unit test to the services, similar to the evapotranspiration

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/core/domain/entity/PWAEntity.py
change the file name to the project pattern
percent_wetted_area_entity

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/core/domain/entity/PWAEntity.py
> +class IBTEntity:
improve the name of the entities, to be more clear.

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/api/v1/responses/percent_wetted_area.py
> +class IBTResponse(BaseModel):
fix the name of response, follow the pattern

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/apps/percent_wetted_area/Readme.md
> +- `ibt_entity`: An instance of the `IBTEntity` class containing the following attributes:
fix these names

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/apps/percent_wetted_area/Readme.md
💯

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/apps/percent_shaded_area/Readme.md
💯

2023-08-07 22:25 UTC, ravellys commented on irrigation_design_system_backend/apps/percent_shaded_area/Readme.md
suggestion: create a flowchart with the input and output of the process. Similar with the thesis literature

2023-08-10 01:19 UTC, ravellys commented on irrigation_design_system_backend/tests/unit/apps/percent_wetted_area/test_reference_percent_wetted_area_service.py
> +        expected_result = Decimal(
same here

2023-08-10 01:20 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/api/v1/responses/percent_wetted_area.py
💯

2023-08-10 01:22 UTC, ravellys reviewed
💯

2023-08-10 22:17 UTC, geanderson-062 commented on irrigation_design_system_backend/tests/unit/apps/percent_shaded_area/test_reference_percent_shaded_area_service.py
> +        expected_result = Decimal(
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/88575dc8bdd0da896a11912d64cd784b96e709a3

2023-08-10 22:17 UTC, geanderson-062 commented on irrigation_design_system_backend/tests/unit/apps/percent_wetted_area/test_reference_percent_wetted_area_service.py
> +        expected_result = Decimal(
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/88575dc8bdd0da896a11912d64cd784b96e709a3

2023-08-10 22:18 UTC, geanderson-062 commented on irrigation_design_system_backend/apps/percent_shaded_area/Readme.md
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/d1a9f69a02f7c15ba83e778ff588c4c06d86f568

2023-08-10 22:19 UTC, geanderson-062 commented on irrigation_design_system_backend/infrastructure/api/v1/responses/percent_wetted_area.py
> +class IBTResponse(BaseModel):
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/e338d9f99a81df4331d68fa3bf6f99def2bfbe1f

2023-08-10 22:19 UTC, geanderson-062 commented on irrigation_design_system_backend/core/domain/entity/PWAEntity.py
> +class IBTEntity:
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/e06b4787629e07f2bf0fae220a3598a68cebe57a

2023-08-10 22:19 UTC, geanderson-062 commented on irrigation_design_system_backend/core/domain/entity/PWAEntity.py
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/e06b4787629e07f2bf0fae220a3598a68cebe57a

2023-08-10 22:20 UTC, geanderson-062 commented on irrigation_design_system_backend/apps/percent_wetted_area/Readme.md
> +- `ibt_entity`: An instance of the `IBTEntity` class containing the following attributes:
https://github.com/PoucaAgua/irrigation-design-system-backend/pull/45/commits/867c03b6fa7deaf466b9257ea5320f3ffabc5926

2023-08-10 22:23 UTC, ravellys approved these changes
💯 awesome

2023-08-10 22:23 UTC, merged