feat: Model of the project, Lateral line and Derivation line
PoucaAgua/irrigation-design-system-backend pull request #49
Opened 2023-08-21 18:16 UTC by evandrosystems

2023-08-21 19:46 UTC, ravellys requested changes
Some requests before the approve

2023-08-21 19:46 UTC, ravellys commented on requirements.txt
> -sqlalchemy==2.0.18
Why did you remove these dependencies?

2023-08-21 19:46 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +    etc = Column(DECIMAL(10, 2), default=0.00)
put the full name of the columns: irn, etc, itn, ... please

2023-08-21 19:46 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +
you forgout the derivationLine FK

2023-08-21 19:46 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +    group_id = Column(String(100))
we need a column with the project description too

2023-08-21 22:34 UTC, evandrosystems commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +    group_id = Column(String(100))
Right

2023-08-21 22:34 UTC, evandrosystems commented on requirements.txt
> -sqlalchemy==2.0.18
I did a pull in main, and then came changes in requirements.txt, but here the dependencies are installed.

2023-08-21 22:36 UTC, evandrosystems commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +    etc = Column(DECIMAL(10, 2), default=0.00)
Right!

2023-08-21 22:39 UTC, evandrosystems commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> +
Perfect! I will make the relationship with the design table

2023-08-22 02:55 UTC, ravellys requested changes

2023-08-22 02:55 UTC, ravellys commented on irrigation_design_system_backend/infrastructure/persistence/models/projects.py
> -    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
here, add the ENum status. 

thes status are:
DRAFT, ACTIVE, INACTIVE

2023-08-22 18:36 UTC, ravellys requested changes

2023-08-22 18:36 UTC, ravellys commented on Makefile
Awesome,

Just put a comment explaining the command and add this on the Readme.md

2023-08-22 18:36 UTC, ravellys commented on Makefile
You can create the make requirements too

2023-08-22 18:45 UTC, evandrosystems commented on Makefile
Right!

2023-08-22 22:57 UTC, ravellys approved these changes
Awesome

2023-08-22 23:09 UTC, merged