Feature/create routine to size the lateral line
PoucaAgua/irrigation-design-system-backend pull request #54
Opened 2023-08-26 20:56 UTC by josafatavares13

2023-08-30 00:58 UTC, ravellys requested changes
please, create the methods requested in comments and create a service to calculate the HF (step 3 and 4 here https://docs.google.com/spreadsheets/d/1QYo1amxhV7rXxUm-2INXj-kYUU8J2QSZ/edit#gid=1017660306)

2023-08-30 00:58 UTC, ravellys commented on irrigation_design_system_backend/apps/calculate_lateral_line/calculate_friction factor.py
Nice!!!

create the unitest please

2023-08-30 00:58 UTC, ravellys commented on irrigation_design_system_backend/apps/calculate_lateral_line/calculate_reynolds.py
Nice!!!

create the unitest, please

2023-08-30 00:58 UTC, ravellys commented on irrigation_design_system_backend/core/domain/entity/lateral_line_entity.py
use this like LateralLineInput

![image](https://github.com/PoucaAgua/irrigation-design-system-backend/assets/57733801/e0eb9419-4b6d-40be-b9e0-f105beacc9f8)

2023-08-30 00:58 UTC, ravellys commented on irrigation_design_system_backend/apps/calculate_lateral_line/calculate_lateral_line.py
here,

you should to create the lateralLineSize

![image](https://github.com/PoucaAgua/irrigation-design-system-backend/assets/57733801/1eef80b2-3e22-483e-bc6d-5194740da3e2)

2023-08-30 00:58 UTC, ravellys commented on irrigation_design_system_backend/core/constants/lateral_line.py
> +  m = Decimal(0.25)
put the complete name of the variables please

2023-09-12 23:23 UTC, josafatavares13 commented on irrigation_design_system_backend/core/constants/lateral_line.py
> +  m = Decimal(0.25)
ok

2023-09-12 23:23 UTC, josafatavares13 commented on irrigation_design_system_backend/core/domain/entity/lateral_line_entity.py
ok

2023-11-07 23:24 UTC, closed without merging